#!/usr/bin/env bash
#
# Cut a GitHub release for PartyHams Logger.
#
#   scripts/release.sh v0.1.0              # build for THIS OS, tag, upload
#   scripts/release.sh v0.1.0 --dry-run    # print every gh/tag step instead
#   scripts/release.sh v0.1.0 --target package-mac-universal
#
# What it does, in order:
#   1. Validate the git tree is clean and the version arg looks sane
#      (vMAJOR.MINOR.PATCH, matching pyproject.toml / partyhams.__version__).
#   2. Create an annotated git tag on the current commit if it doesn't exist.
#   3. Build the standalone artifact(s) for the current OS via `make <target>`.
#   4. Compute dist/SHA256SUMS and dist/MD5SUMS over the built artifacts.
#   5. Create the GitHub release (or upload to it if it already exists) with
#      the `gh` CLI, attaching the artifacts + both checksum files.
#
# PyInstaller can't cross-compile, so this only ever produces artifacts for the
# OS/arch it runs on. Run it once per target platform (or in a CI matrix) and
# upload into the same release tag — see docs/RELEASING.md and docs/PACKAGING.md.

set -euo pipefail

# ---- locate the repo root (this script lives in scripts/) -----------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

DIST_DIR="$REPO_ROOT/dist"

# ---- pretty output --------------------------------------------------------
info()  { printf '>> %s\n' "$*"; }
warn()  { printf 'WARNING: %s\n' "$*" >&2; }
die()   { printf 'ERROR: %s\n' "$*" >&2; exit 1; }

usage() {
    cat >&2 <<'EOF'
usage: scripts/release.sh <version> [--dry-run] [--target <make-target>] [--notes <file>]

  <version>            release tag, e.g. v0.1.0
  --dry-run            print the tag/gh commands instead of running them
  --target <target>    make package target to build (default: package)
                       e.g. package-mac-universal, package-appimage, package-deb
  --notes <file>       use <file> as the release notes body (default: autogenerated)
EOF
    exit 2
}

# ---- parse args -----------------------------------------------------------
VERSION=""
DRY_RUN=0
MAKE_TARGET="package"
NOTES_FILE=""

while [ $# -gt 0 ]; do
    case "$1" in
        --dry-run)      DRY_RUN=1; shift ;;
        --target)       MAKE_TARGET="${2:-}"; [ -n "$MAKE_TARGET" ] || usage; shift 2 ;;
        --target=*)     MAKE_TARGET="${1#*=}"; shift ;;
        --notes)        NOTES_FILE="${2:-}"; [ -n "$NOTES_FILE" ] || usage; shift 2 ;;
        --notes=*)      NOTES_FILE="${1#*=}"; shift ;;
        -h|--help)      usage ;;
        -*)             die "unknown option: $1" ;;
        *)
            [ -z "$VERSION" ] || die "unexpected extra argument: $1"
            VERSION="$1"; shift ;;
    esac
done

[ -n "$VERSION" ] || usage

# ---- run a command, or just echo it in dry-run mode -----------------------
run() {
    if [ "$DRY_RUN" -eq 1 ]; then
        printf 'DRY-RUN:'; printf ' %q' "$@"; printf '\n'
    else
        "$@"
    fi
}

# ---- tool guards ----------------------------------------------------------
command -v git  >/dev/null 2>&1 || die "'git' not found on PATH."
command -v make >/dev/null 2>&1 || die "'make' not found on PATH. Install build tools and retry."
# gh is only strictly needed for the release step; check it up front so we fail
# fast rather than after a long build (skip the hard failure in dry-run).
if ! command -v gh >/dev/null 2>&1; then
    if [ "$DRY_RUN" -eq 1 ]; then
        warn "'gh' (GitHub CLI) not found — dry-run will still print its commands."
    else
        die "'gh' (GitHub CLI) not found. Install it and run 'gh auth login' (see docs/RELEASING.md)."
    fi
fi

# ---- validate the version string ------------------------------------------
case "$VERSION" in
    v[0-9]*.[0-9]*.[0-9]*) : ;;
    *) die "version must look like vMAJOR.MINOR.PATCH (e.g. v0.1.0), got: $VERSION" ;;
esac
BARE_VERSION="${VERSION#v}"   # strip leading 'v' to compare with pyproject

# ---- cross-check against pyproject.toml / __version__ ---------------------
PYPROJECT_VERSION="$(
    sed -n 's/^version[[:space:]]*=[[:space:]]*"\([^"]*\)".*/\1/p' pyproject.toml | head -n1
)"
INIT_VERSION="$(
    sed -n 's/^__version__[[:space:]]*=[[:space:]]*"\([^"]*\)".*/\1/p' \
        src/partyhams/__init__.py | head -n1
)"

[ -n "$PYPROJECT_VERSION" ] || warn "could not read version from pyproject.toml"
[ -n "$INIT_VERSION" ]      || warn "could not read __version__ from src/partyhams/__init__.py"

if [ "$PYPROJECT_VERSION" != "$INIT_VERSION" ]; then
    warn "pyproject.toml ($PYPROJECT_VERSION) and partyhams.__version__ ($INIT_VERSION) disagree."
fi
if [ "$BARE_VERSION" != "$PYPROJECT_VERSION" ]; then
    warn "tag $VERSION does not match pyproject.toml version $PYPROJECT_VERSION."
    warn "Bump 'project.version' in pyproject.toml and partyhams.__version__ to $BARE_VERSION first if this is wrong."
fi

# ---- require a clean tree on the commit being released --------------------
if [ -n "$(git status --porcelain)" ]; then
    die "working tree is not clean. Commit or stash changes before releasing.
     (git status):
$(git status --short)"
fi
CURRENT_COMMIT="$(git rev-parse --short HEAD)"
CURRENT_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
info "releasing $VERSION from $CURRENT_BRANCH @ $CURRENT_COMMIT"

# ---- create the annotated tag if it doesn't exist -------------------------
if git rev-parse -q --verify "refs/tags/$VERSION" >/dev/null; then
    EXISTING_TAG_COMMIT="$(git rev-list -n1 "$VERSION")"
    if [ "$EXISTING_TAG_COMMIT" != "$(git rev-parse HEAD)" ]; then
        warn "tag $VERSION already exists but points at a different commit ($EXISTING_TAG_COMMIT)."
    else
        info "tag $VERSION already exists (points at HEAD) — reusing it."
    fi
else
    info "creating annotated tag $VERSION"
    run git tag -a "$VERSION" -m "PartyHams Logger $VERSION"
    info "remember to push the tag:  git push origin $VERSION"
fi

# ---- build the artifact(s) for this OS ------------------------------------
info "building artifacts via 'make $MAKE_TARGET' (this can take a while)"
if [ "$DRY_RUN" -eq 1 ]; then
    printf 'DRY-RUN: would run: make %q\n' "$MAKE_TARGET"
else
    make "$MAKE_TARGET"
fi

# ---- gather the built artifacts from dist/ --------------------------------
# We checksum & upload the top-level entries PyInstaller / the packagers leave
# in dist/ (the .app bundle, the per-OS folder, AppImage/.deb/.rpm, etc.),
# but never the checksum files themselves.
ARTIFACTS=()   # basenames, relative to dist/
if [ "$DRY_RUN" -eq 1 ] && [ ! -d "$DIST_DIR" ]; then
    info "(dry-run) dist/ not built — would checksum & upload artifacts from dist/"
else
    for entry in "$DIST_DIR"/*; do
        [ -e "$entry" ] || continue          # no glob match -> literal '*'
        name="$(basename "$entry")"
        case "$name" in
            SHA256SUMS|MD5SUMS) continue ;;
        esac
        ARTIFACTS+=("$name")
    done
    [ "${#ARTIFACTS[@]}" -gt 0 ] || die "no artifacts found in dist/ after build."
    info "artifacts: ${ARTIFACTS[*]}"
fi

# ---- checksums (computed over the same names, run from inside dist/) -------
# Picks the available tool per OS: shaXsum on Linux, shasum -a on macOS.
sha256_tool() {
    if command -v sha256sum >/dev/null 2>&1; then echo "sha256sum"; \
    elif command -v shasum  >/dev/null 2>&1; then echo "shasum -a 256"; \
    else return 1; fi
}
md5_tool() {
    if command -v md5sum >/dev/null 2>&1; then echo "md5sum"; \
    elif command -v md5  >/dev/null 2>&1; then echo "md5 -r"; \
    else return 1; fi
}

write_checksums() {
    local out="$1"; shift          # output filename (relative to dist/)
    local tool="$1"; shift         # checksum command
    local -a names=("$@")
    : > "$out"
    local n
    for n in "${names[@]}"; do
        # hash files directly; recurse into directories (e.g. the per-OS folder
        # / .app bundle) so every contained file is covered.
        if [ -d "$n" ]; then
            find "$n" -type f -print0 | sort -z | while IFS= read -r -d '' f; do
                $tool "$f"
            done >> "$out"
        else
            $tool "$n" >> "$out"
        fi
    done
}

if [ "$DRY_RUN" -eq 1 ] && [ "${#ARTIFACTS[@]}" -eq 0 ]; then
    info "(dry-run) would write dist/SHA256SUMS and dist/MD5SUMS"
else
    SHA_TOOL="$(sha256_tool)" || die "no sha256 tool found (need sha256sum or shasum)."
    MD5_TOOL="$(md5_tool)"    || die "no md5 tool found (need md5sum or md5)."
    info "computing checksums (sha256: $SHA_TOOL, md5: $MD5_TOOL)"
    (
        cd "$DIST_DIR"
        write_checksums SHA256SUMS "$SHA_TOOL" "${ARTIFACTS[@]}"
        write_checksums MD5SUMS    "$MD5_TOOL" "${ARTIFACTS[@]}"
    )
    info "wrote dist/SHA256SUMS and dist/MD5SUMS"
fi

# ---- assemble the list of files to upload (relative to dist/) -------------
UPLOAD_FILES=()
if [ "${#ARTIFACTS[@]}" -gt 0 ]; then
    for a in "${ARTIFACTS[@]}"; do
        UPLOAD_FILES+=("dist/$a")
    done
fi
UPLOAD_FILES+=("dist/SHA256SUMS" "dist/MD5SUMS")

# ---- release notes --------------------------------------------------------
NOTES_ARGS=()
if [ -n "$NOTES_FILE" ]; then
    [ -f "$NOTES_FILE" ] || die "notes file not found: $NOTES_FILE"
    NOTES_ARGS=(--notes-file "$NOTES_FILE")
else
    NOTES_ARGS=(--generate-notes)
fi

# ---- create or update the GitHub release ----------------------------------
# True only if gh is present AND the release already exists. In dry-run without
# gh we can't know, so treat it as "create" (the common first-cut case).
release_exists() {
    command -v gh >/dev/null 2>&1 || return 1
    gh release view "$VERSION" >/dev/null 2>&1
}

if release_exists; then
    info "release $VERSION already exists — uploading artifacts (clobbering existing assets)"
    run gh release upload "$VERSION" "${UPLOAD_FILES[@]}" --clobber
else
    info "creating GitHub release $VERSION"
    run gh release create "$VERSION" "${UPLOAD_FILES[@]}" \
        --title "PartyHams Logger $VERSION" \
        "${NOTES_ARGS[@]}"
fi

info "done."
if [ "$DRY_RUN" -eq 1 ]; then
    info "(this was a dry-run — no tag was created and nothing was pushed to GitHub)"
fi
